---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-cert
  namespace: vpn
  labels:
    "use-http01-solver": "true"
spec:
  commonName: sabnzbd.justsem.org
  secretName: sabnzbd-cert
  dnsNames:
    - sabnzbd.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
