apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    hostname: sabnzbd
    image:
      repository: ghcr.io/onedr0p/sabnzbd
      tag: 4.0.1@sha256:8c1f42be3ae0770ad80921780e22f0cdc09197483752ec13a808a35e60bb5496
    imagePullSecrets:
      - name: justsem-ghcr
    env:
      TZ: "Europe/Amsterdam"
      HOST_WHITELIST_ENTRIES: "sabnzbd.justsem.org"
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: openebs-hostpath
      downloads:
        enabled: true
        type: hostPath
        mountPath: /downloads/sabnzbd
        hostPath: /opt/storage/sabnzbd
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.middlewares: vpn-sabnzbd-auth@kubernetescrd,vpn-security-headers@kubernetescrd
        hosts:
        - host: &host "sabnzbd.justsem.org"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: sabnzbd-cert
          hosts:
          - *host
