---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: conduit-cert
  namespace: matrix
  labels:
    "use-http01-solver": "true"
spec:
  commonName: conduit.justsem.org
  secretName: conduit-cert
  dnsNames:
    - conduit.justsem.org
    - justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
