apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: matrix
data:
  matrix.conf: |
    server {
      server_name justsem.org;
        listen      80 default_server;

        location /.well-known/matrix/server {
          return 200 '{"m.server": "justsem.org:443"}';
          types { } default_type "application/json; charset=utf-8";
        }

       location /.well-known/matrix/client {
          return 200 '{"m.homeserver": {"base_url": "https://justsem.org"}}';
          types { } default_type "application/json; charset=utf-8";
          add_header "Access-Control-Allow-Origin" *;
       }

       location / {
          return 404;
       }
    }

