apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: conduit
  namespace: matrix
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    runtimeClassName: gvisor
    image:
      repository: matrixconduit/matrix-conduit
      tag: latest
    env:
      CONDUIT_SERVER_NAME: "justsem.org"
      CONDUIT_DATABASE_BACKEND: "rocksdb"
      CONDUIT_ALLOW_REGISTRATION: "false"
      CONDUIT_ALLOW_FEDERATION: "true"
      CONDUIT_MAX_REQUEST_SIZE: "20000000"
      CONDUIT_TRUSTED_SERVERS: "[\"matrix.org\", \"sciuro.org\"]"
      CONDUIT_MAX_CONCURRENT_REQUESTS: "100"
      CONDUIT_LOG: "warn,rocket=off,_=off,sled=off"
      CONDUIT_PORT: "6167"
      CONDUIT_DATABASE_PATH: "/var/lib/matrix-conduit/"
      CONDUIT_ADDRESS: "0.0.0.0"
    persistence:
      db:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        mountPath: "/var/lib/matrix-conduit"
        size: 16Gi
      nginx:
        enabled: true
        type: configMap
        name: nginx-config
        mountPath: /etc/nginx/conf.d/
#      nginx:
#        enabled: true
#        type: configMap
#        name: nginx-config
#        mountPath: ./nginx
#    podSecurityContext:
#      runAsUser: 568
#      runAsGroup: 568
#      fsGroup: 568
#      fsGroupChangePolicy: "OnRootMismatch"
#    probes:
#      liveness:
#        enabled: true
#        custom: true
#        spec:
#          exec:
#            command:
#              - /usr/bin/env
#             - bash
#              - -c
#              - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
#          failureThreshold: 5
#          initialDelaySeconds: 60
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 10
    service:
      main:
        ports:
          http:
            port: 6167
          well-known:
            port: 80
    additionalContainers:
      well-known:
        image: nginx:latest
        volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/conf.d/
