apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: justsem-k8s-flux-runner
  namespace: arc
spec:
  replicas: 1
  dockerdWithinRunnerContainer: false
  repository: justSem/k8s-flux
  selector:
    matchLabels:
      app: k8s-flux
  serviceName: k8s-flux
  template:
    metadata:
      labels:
        app: k8s-flux
    spec:
      containers:
      - name: runner
        image: summerwind/actions-runner:latest
#        env: []
        resources:
          limits:
            cpu: "4.0"
            memory: "12Gi"
          requests:
            cpu: "1.0"
            memory: "4Gi"
#      - name: docker
#        resources:
#          limits:
#            cpu: "4.0"
###            memory: "12Gi"
#          requests:
#            cpu: "1.0"
#            memory: "4Gi"
