---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flux-receiver-cert
  namespace: flux-system
spec:
  commonName: flux.d002.servers.justsem.org
  secretName: flux-receiver-cert
  dnsNames:
    - flux.d002.servers.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
