apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: datadog
      version: 3.30.4
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
      interval: 5m
  values:
    datadog:
      site: 'datadoghq.eu'
      logs:
        enabled: true
        containerCollectAll: true
  valuesFrom:
  - kind: Secret
    name: values
    valuesKey: values.yaml
    optional: false
