apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-cert
  namespace: vpn
  labels:
    "use-http01-solver": "true"
spec:
  commonName: radarr.justsem.org
  secretName: radarr-cert
  dnsNames:
    - radarr.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
