---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-cert
  namespace: vpn
  labels:
    "use-http01-solver": "true"
spec:
  commonName: prowlarr.justsem.org
  secretName: prowlarr-cert
  dnsNames:
    - prowlarr.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
