apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.5.0.3390
    imagePullSecrets:
      - name: justsem-ghcr
    env:
      TZ: "Europe/Amsterdam"
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: openebs-hostpath
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.middlewares: vpn-prowlarr-auth@kubernetescrd,vpn-security-headers@kubernetescrd
        hosts:
        - host: &host "prowlarr.justsem.org"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: prowlarr-cert
          hosts:
          - *host
