---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-cert
  namespace: vpn
  labels:
    "use-http01-solver": "true"
spec:
  commonName: sonarr.justsem.org
  secretName: sonarr-cert
  dnsNames:
    - sonarr.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
