apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MdWGCk2GUyVf8E/LJRHFgxrTnTZpEYVtu3IiO0DbfGfJcow5DW+RbL3MKxyi6/AmpDtBtlOpQ256eE+pGPaBXA3G+7DgdDZb4tv+pMyaZZPsOP3gjaox8DeJY8bLSloUnXRD5smryVX5fVKxNAy70oXxK12Avoq5JczkTAQEOrQIwtjBy7IzUTPDWhpGNoq5DgbqOkBjB8evjTiq5VRJrLAwgjULrC3F3OIPllt4ZxKJCV1KIGRlZW5RFlAz5JiVp5bKKfr5EibFDm8qOBwLVL9IlgmjaJqX4gmj3sIun+BdVNaKy7kl1A==,iv:JsdD69i/BpVNqIviGPUWmbRhquGsVeFGT/RW1P6yJUg=,tag:3YcUcKAPi9wFpxYWo2lv3Q==,type:str]
kind: Secret
metadata:
    name: justsem-ghcr
    namespace: vpn
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-06T22:13:54Z"
    mac: ENC[AES256_GCM,data:HElpKwS9BJ9l2MZk9N8C6W7mULKCk8LjXJTIQAZ2cc4iYUWLiPv8C7BO45NxKiB8h0rjRjSGLURDX6XSiVXn3q23w8OEWvIBt/gmsdb28YMzPiWkCZIxohZDC7YOx+pss6/M3ZbXIk2YvJ9107MzemlmUSwYgzAsyp6oWWgCKbM=,iv:zSbba0cKwS5q0TNwQ2kO1iU1MHiRxLZAnKLsf+iGV+o=,tag:ySoon6WC6e5MXkSGxt2FuQ==,type:str]
    pgp:
        - created_at: "2022-12-06T22:13:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwdUmVO8UyRmAQ/+Imy4F8y0yVS4ZnpWYuksTqy5MzuX8hgbHQqeHidU6XTT
            ozorUpnlfLYqCY3xz2bK6rPsxnPvh3KnDhr22W53gAZHpodjpjUCIudVfryVibuV
            DqsGg/J89F8zEQvizEWKKLc09/t/r6wjCish3WwE7UQ3vgPH1IwR2xsgo9AdsF5W
            X8PJSiEh5bJ3wMrKwNXKdLqKoThfIREH7ElXpJXyTweiejVcROiN6AIQxcbQYTY+
            gFEkmggaMiUVXb77AicWwkM/f8dowMf/VFVbhDjsd7o6I490hVS1QqGlrjnvXY+M
            yL5S3ja2vwKu66GvWboAt6RHAT5IEYpCncgnPNtOeLxGZ+0qM73fEk6T1CaYiv93
            9Hkqb019HQucxkjyNa+DS+/25EzEVbuvu1DLcJfJ9e24nuN7TMaGm8CKkP2MJlEr
            VJCgfNvPS3GhMQk+R3L5TXIjIIm7H6+rLv55L1UbK2SyJEP53jbfT4AGcivOemzL
            3tnLCQB20E4zOALVtp7nZ23v4KLelBgQ7MhLh4G4/H5XZvXms+/yOETTifeXbTzQ
            BhzZEbpXcfPSxttHl8lcDIo4v62ir4KYVGIAgn52m3HcEnHI7m4T6YW5S6YhjJbT
            +Ks3v0n7YSB13ia+bGLjRnJye/L1GpNP6yXrSEfOz9bu27Mn+zbo1gIg9sR0Kp7S
            XgGhobHz4oiPCvNsPkYwD4yM8eusBvqhuW0xQUDnZ9n2D7GIUgx20UYYAQvJGcWm
            t9WG1VYFctvuw8tpQjxJhD7UNWw4VDsSUxdSdF0d/5e2PYq0abkYx9vqKJbHD7s=
            =jb+v
            -----END PGP MESSAGE-----
          fp: B194147D46676F527F2C1A33AC4C1FF17C9B79D9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
