apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
  labels:
    # Avoid variable substitution of shell variables bellow
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-helm-charts
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml
  values:
#    securityContext:
#      privileged: true
#      capabilities:
#        add:
#          - NET_ADMIN
#          - SYS_MODULE
#          - NET_RAW
    persistence:
      shared:
        enable: true
        type: emptyDir
        mountPath: /shared

    image:
      repository: ghcr.io/angelnu/pod-gateway
      # I am using dev version for testing - others should be using latest
      tag: v1.8.1
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        # Use dev version
        pullPolicy: Always
        tag: v3.9.0
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.34.1

        env:
        - name:  VPN_SERVICE_PROVIDER
          value: mullvad
        - name:  VPN_TYPE
          value: wireguard
        - name:  VPN_INTERFACE
          value: wg0
        - name:  FIREWALL
          value: "off"
        - name:  DOT
          value: "off"
        - name:  "HEALTH_VPN_DURATION_INITIAL"
          value: '30s'
        - name:  "HEALTH_TARGET_ADDRESS"
          value: "am.i.mullvad.net:443"
        # - name:  WIREGUARD_PRIVATE_KEY
        #   value: set in secret
        # - name:  WIREGUARD_PRESHARED_KEY
        #   value: set in secret
        # - name:  WIREGUARD_ADDRESSES
        #   value: set in secret
        # - name:  SERVER_COUNTRIES
        #  value: Belgium
        
        envFrom:
          - secretRef:
              name: mullvad
#        securityContext:
#          capabilities:
#            add:
#              - NET_ADMIN


        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - 'if [ $(wget -q -O- https://am.i.mullvad.net/country) == "Sweden" ]; then exit 0; else exit $?; fi'
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3

        networkPolicy:
          enabled: true

          egress:
            - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
              ports:
              # VPN traffic
              - port: 51820
                protocol: UDP
            - to:
              - ipBlock:
                  cidr: 10.0.0.0/8
              - ipBlock:
                  cidr: 192.168.0.0/16

    routed_namespaces:
    - vpn
    
    settings:
      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0
      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: true
      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: "51820"
      # -- Traffic to these IPs will be send through the K8S gateway
#      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 178.63.75.45/32 185.213.154.69/32 10.32.0.0/16"
#      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 178.63.75.45/32 185.213.154.69/32 10.32.0.0/16"
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.0.0/16"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.0.0/16"
#      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
#      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      VXLAN_ID: 42
      VXLAN_IP_NETWORK: 172.16.0
      DNS_LOCAL_CIDRS: "local cluster.local"
      #K8S_DNS_IPS: "10.43.0.10"
    
    # -- settings to expose ports, usually through a VPN provider.
    # NOTE: if you change it you will need to manually restart the gateway POD
    publicPorts:
    - hostname: deluge
      IP: 10
      ports:
      - type: udp
        port: 56303
      - type: tcp
        port: 56303
    - hostname: qbitanime
      IP: 20
      ports:
      - type: udp
        port: 60830
      - type: tcp
        port: 60830
    
