apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      tag: v3.1.2
    env:
      TZ: "Europe/Amsterdam"
      LOG_LEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 8191
    ingress:
      main:
        enabled: false
