---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: themepark-cert
  namespace: theme-park
  labels:
    "use-http01-solver": "true"
spec:
  commonName: themepark.justsem.org
  secretName: themepark-cert
  dnsNames:
    - themepark.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
