apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-sytem
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 4.5.0
      sourceRef:
        kind: HelmRepository
        name: kubereboot-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/kubereboot/kured
      tag: 1.21.1
    configuration:
      startTime: "3:00"
      endTime: "6:00"
      timeZone: "Europe/Amsterdam"
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
    #metrics:
    #  create: true
  valuesFrom:
  - kind: Secret
    name: "kured-values"
    optional: false
