apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: settings
  namespace: flux-system
spec:
  interval: 10m5s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/settings/production
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  #postBuild:
  #  substitute: {}
  #  substituteFrom:
  #  - kind: ConfigMap
  #    name: global-settings
  #  - kind: Secret
  #    name: global-secrets
  #  - kind: ConfigMap
  #    name: cluster-settings
  #  - kind: Secret
  #    name: cluster-secrets
