apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: factoriotcp
  namespace: games
spec:
  entryPoints:
  - factoriotcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: factorio
      port: 27015
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: factorioudp
  namespace: games
spec:
  entryPoints:
    - factorioudp
  routes:
  - services:
    - name: factorio
      port: 34197

