apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: factorio
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    runtimeClassName: gvisor
    image:
      repository: factoriotools/factorio
      tag: 1.1.76
    env:
      TZ: "Europe/Amsterdam"
      USERNAME: "justSem"
      PORT: "34197"
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: openebs-hostpath
        mountPath: /factorio
        size: 25Gi
    probes:
      liveness:
        enabled: true
    service:
      main:
        ports:
          http:
            enabled: false
          game:
            port: 34197
            enabled: true
            primary: false
            protocol: UDP
            targetPort: 34197
          steam:
            enabled: true
            primary: true
            port: 27015
            protocol: TCP
            targetPort: 27015
    ingress:
      main:
        enabled: false
