---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: znc-cert
  namespace: vpn
  labels:
    "use-http01-solver": "true"
spec:
  commonName: znc.justsem.org
  secretName: znc-cert
  dnsNames:
    - znc.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
