apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: znc
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    initContainers:
      init-config:
        name: init-config
        image: znc:1.8.2
        command: ['/bin/sh', '-c', "until [ -f /znc-data/configs/znc.conf ]; do echo waiting for znc.conf; sleep 2; done"]
        volumeMounts:
          - mountPath: /znc-data
            name: znc-data
    image:
      repository: znc
      tag: 1.8.2
    imagePullSecrets:
      - name: justsem-ghcr
    env:
      TZ: "Europe/Amsterdam"
    persistence:
      znc-data:
        enabled: true
        type: pvc
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 100Mi
      znc-cert:
        enabled: true
        type: secret
        mountPath: /ssl
        name: znc-cert
    service:
      main:
        ports:
          http:
            port: 6667
          znc:
            port: 6697
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.middlewares: vpn-security-headers@kubernetescrd,vpn-znc-auth@kubernetescrd
        hosts:
        - host: &host "znc.justsem.org"
          paths:
          - path: /
            pathType: Prefix

        tls:
        - secretName: znc-cert
          hosts:
          - *host
          
