apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-static-data
  namespace: authentik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openebs-hostpath
