apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
  namespace: authentik
spec:
  commonName: sso.justsem.org
  secretName: authentik-cert
  dnsNames:
    - sso.justsem.org
    - id.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
