apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-logos
  namespace: authentik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: openebs-hostpath
