apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:f3zYwQXgwhnWqDIQw0BeO37HKwVZZ85JzHD0YHNmeWuo57cy65gQGFSLLoq7TRLrDkBr6Lmhnh+cf2TWBPnCNUd9b59T20+/N115Vkw+iayH8RW6o/lDbP/CpMDfb2MgaqCMxAV4i9OKq8EVI7ou1RMsSTv0hXrVbQtIw4th55XvyiCiWEcZMiIwBMhi7ZKkg/5K9xl2VfRPf000raI5CKi5DTkyXIUe815JhV5SHX97c/ep3bkrcyzZ6ncqF5MQUrtPZmAOxT2zhTPNE4ajd8mo96+wNjCXGfxRZnCaKzZ0Zb1NgJbZ7zjP7mL+6SfdMGqtohiPyi+gmwV6Pr8t6OZTxqLB4ipmBIpwL6/UuwEKRaU4E8jUWUuKAVdg+zHkjMtK5a/cw85OIu42WsTLNUHFBNkQzMFpvNd2nMWo6solYLjHlTkINV0+uUgCcb6a3WevWfxyxEQ3LjEdLa3s+hImQXTHkZCKxacA06GrkaWNgdEoi9ksiMsXbkSLSKw2idyrTZ6uNXMNUggNxcDHy2Gwpz6Y7bYVotaItzNMD7yGWupzYTnaYQ+UOQ2uAQSbXs8xBgidHa36G3RHYNeVjudhWAa5Gp5wCa1cWge3vlHdPCmYmcnye1y5nh6VsMgUhR7ghYzcZzynu247fqAnGz//R6O+aE6YxXgYQD+LzNRK9hYUPcohv66OUmUNVr7lZHk1mBWTkD8LzFc/14YispXtDd8Pto8yOO5tryleNlSF865ZWFuVOAMQ954UVwra3GTBabtu9DFGQ/5Oy8/Yx7MNIA4ECapkvRwucFpEWVL1uvS6xzT10TVB9svTEOa6kbOW/AlQR7CuO9XK,iv:0Nu4aTyon2E7qCaK1QrInj71iVPGmrRpKlhm5V0d2KU=,tag:pUNHjsW5SbVwNZgUaMBghA==,type:str]
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-12T15:26:24Z"
    mac: ENC[AES256_GCM,data:PPKTcwMNu4EU1pPv64a2J8H/oEgvLuhVTdnbGvL1LxhSt/Aa5h+58PyCrZIJUS34ULuzYYWpwunN1TT6VMRWudfrXF302Gv84qeiS2c+Y+H4eyOx5UWHIJO5sDOmdeFWjiFJFbyItmjpGzVe+3rrpmmomlFXMS9Dmj840/Gd/Qo=,iv:kJSp0OlOc1EBxbW0FMQs2V+QgRPYoQIEBc9ZriQyXEg=,tag:DxCdQPrsHb2Q95qparyHzA==,type:str]
    pgp:
        - created_at: "2023-02-12T15:26:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwdUmVO8UyRmAQ/9Hvgl1o/MGEZ7WcXu9jVgZzOsjw55ICij5uBErqWUzQx+
            BwgljdfvOSbo5GXoVQVnrQQA3Rz1R224gZloHegAY5K9OEme9/aT/Jcel+soASOa
            h8YlorjzCyG7zD6i3XN96PM3fN9XGRCKfcIs8C8fH7E+Wd45L4n6tNg2jnFjHxhT
            HCaoihgQiSgkVdmB00o45uEg1Dinl+WyORao9+iqW4zCgFAZLrS9fxqeVbDw+dWO
            AD/kzU/6s+jQXKv1QKasp8tdtyU+75M0vWYoq7RkikJBN5Q6zNKPXi/vjUjymgZk
            FXCxkJaWlvEZuS64Ns3lPgffFZ5ujR7C5JskFASFU+8PBUuXjmTWhIcHEHCGI+HL
            ptqaxbILsrz2bZhxg2LVsZFP/2TkkmzdEzQVmp64FPFM84QmoGQaV2E2an2RtshD
            0CU8YvhUhLHtUg+SgeYp3hM+r7RqYnmZ69c9m134Vhhr9Vpdfqga2tUXLL7mYErA
            an+nOYBJ2fII7MXGDTMGFGhuSC0Ihh9MWZRtlHv16+gcwO1BbcE28D08or0kVKTw
            AmNzyQ4V3DsHh15qt4leeQeXZROQxD7i1FJQLjFGDtMkSeHfLed1h2mQkWK1FCZk
            e+YYXK0Z9p87N53chfV22E9o+7UnN0xt9SggswdXLpGZ7HE0gufvIvZ139W0vW7S
            XgGfF4P7RmnVflJldm3er51ONW700e2F4ou7ln2YyoB0E7xPK8CMnU2q+PXsGzrN
            MmkGAMvz53BPcxMvqMrNdOPDLwac38ouDBbPUOJA6VTVcsWsvFxHwlL89vUDg+k=
            =lcHW
            -----END PGP MESSAGE-----
          fp: B194147D46676F527F2C1A33AC4C1FF17C9B79D9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
