---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-cert
  namespace: default
spec:
  commonName: filter.internal.justsem.org
  secretName: adguard-cert
  dnsNames:
    - filter.internal.justsem.org
    - adguard.internal.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
