apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m5s
  dependsOn:
    - name: core
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/raspberry
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
#  postBuild:
#    substitute: {}
#    substituteFrom:
#    - kind: ConfigMap
#      name: global-settings
#    - kind: Secret
#      name: global-secrets
#    - kind: ConfigMap
#      name: cluster-settings
#    - kind: Secret
#      name: cluster-secrets
