apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: arc-helm-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://actions-runner-controller.github.io/actions-runner-controller
  timeout: 15m
