apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whatsapp-bridge-postgres
  namespace: matrix
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.2.7
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      storageClass: "openebs-hostpath"
      postgresql:
        auth:
          existingSecret: "postgres-creds"
          secretKeys:
            adminPasswordKey: "admin-pw"
            userPasswordKey: "user-pw"
            replicationPasswordKey: "repl-pw"
    primary:
      persistence:
        storageClass: "openebs-hostpath"

