apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart: 
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs-helm-charts
        namespace: flux-system
  values:
    varDirectoryPath:
      baseDir: "/opt/hostpath/openebs"
    localprovisioner:
      enabled: true
      basePath: "/opt/hostpath/"
      hostPathClass:
        enabled: true
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    jiva:
      enabled: false
    ndmExporter:
      enabled: false 
  
