---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-cert
  namespace: vpn
  labels:
    "use-http01-solver": "true"
spec:
  commonName: lidarr.justsem.org
  secretName: lidarr-cert
  dnsNames:
    - lidarr.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
