apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: lidarr-auth
  namespace: vpn
spec:
  forwardAuth:
    address: https://lidarr.justsem.org/outpost.goauthentik.io/auth/traefik
    authResponseHeaders:
    - X-authentik-username
    - X-authentik-groups
    - X-authentik-email
    - X-authentik-name
    - X-authentik-uid
    - X-authentik-jwt
    - X-authentik-meta-jwks
    - X-authentik-meta-outpost
    - X-authentik-meta-provider
    - X-authentik-meta-app
    - X-authentik-meta-version
    trustForwardHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr-traefik-ingress
  namespace: vpn
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`lidarr.justsem.org`)
      kind: Rule
      priority: 10
      middlewares:
        - name: lidarr-auth
          namespace: vpn
        - name: security-headers
          namespace: vpn
      services:
        - kind: Service
          name: lidarr
          passHostHeader: true
          namespace: vpn
          port: 8686
    - match: Host(`lidarr.justsem.org`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-vpn
          port: 9000
  tls:
    secretName: lidarr-cert
