apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/lidarr
      tag: 1.1.4.3027
    imagePullSecrets:
      - name: justsem-ghcr
    env:
      TZ: "Europe/Amsterdam"
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: openebs-hostpath
      storage:
        enabled: true
        type: hostPath
        mountPath: /media
        hostPath: /opt/storage/streaming/jellyfin
      qbit:
        enabled: true
        type: hostPath
        mountPath: /downloads/qbit
        hostPath: /opt/storage/qbit
      sabnzbd:
        enabled: true
        type: hostPath
        mountPath: /downloads/sabnzbd
        hostPath: /opt/storage/sabnzbd
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-vpn.vpn.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://lidarr.justsem.org//outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |-
              proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://themepark.justsem.org/css/base/lidarr/overseerr.css"></head>';
            sub_filter_once on;
        hosts:
        - host: &host "lidarr.justsem.org"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
