apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: "2.24"
    env:
      TEMPLATE_NAME: "ghost"
#    podSecurityContext:
#      runAsUser: 568
#      runAsGroup: 568
#      fsGroup: 568
#      fsGroupChangePolicy: "OnRootMismatch"
    probes:
      liveness:
        enabled: false
    service:
      main:
        ports:
          http:
            port: 8080
