apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-cert
  namespace: jellyfin
spec:
  commonName: streaming.justsem.org
  secretName: jellyfin-cert
  dnsNames:
    - streaming.justsem.org
    - jellyfin.justsem.org
  issuerRef:
    name: le-hetzner
    kind: ClusterIssuer
