apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: ombi
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    image:
      repository: lscr.io/linuxserver/ombi
      tag: 4.39.1
    imagePullSecrets:
      - name: justsem-ghcr
    env:
      TZ: "Europe/Amsterdam"
      PUID: "1000"
      GUID: "1000"
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: openebs-hostpath
        mountPath: "/config"
#    podSecurityContext:
#      runAsUser: 568
#      runAsGroup: 568
#      fsGroup: 568
#      fsGroupChangePolicy: "OnRootMismatch"
#    probes:
#      liveness:
#        enabled: true
#        custom: true
#        spec:
#          exec:
#            command:
#              - /usr/bin/env
#              - bash
#              - -c
#              - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
#          failureThreshold: 5
#          initialDelaySeconds: 60
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 10
    service:
      main:
        ports:
          http:
            port: 3579
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.middlewares: ombi-security-headers@kubernetescrd
        hosts:
        - host: &host "ombi.justsem.org"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: ombi-cert
          hosts:
          - *host
